### ISSUE TITLE
Problem with having a single unit test

### ISSUE THREAD

**Issue by vieiralucas** [chaijs/get-func-name#10]
Currently unit tests for `get-func-name` are so tiny and simple that I can just copy and paste it over here 😄 
```js
'use strict';
var assert = require('simple-assert');
var getFuncName = require('..');
describe('getFuncName', function () {
  it('getFuncName', function () {
    // Asserting that `getFuncName` behaves correctly
    function /*one*/correctName/*two*/() { // eslint-disable-line no-inline-comments, spaced-comment
      return 0;
    }
    function withoutComments() {
      return 1;
    }

    var anonymousFunc = (function () {
      return function () { // eslint-disable-line func-style
        return 2;
      };
    }());
    assert(getFuncName(correctName) === 'correctName');
    assert(getFuncName(withoutComments) === 'withoutComments');
    assert(getFuncName(anonymousFunc) === '');
  });
});
```
I know this is beautiful, but...

- If the test fails, we wont be able to tell what's going on just by reading the message.
<img width="502" alt="screen shot 2016-10-11 at 9 20 48 pm" src="https://cloud.githubusercontent.com/assets/7764293/19293249/aad4586c-8ff8-11e6-8abc-ee9bad202214.png">
What have I broke here? Imagine if this fails only in IE running over saucelabs 😸.

- If this keeps growing I'm afraid that this can become very confusing like the [utilities tests](https://github.com/chaijs/chai/blob/cc79e11b511ecbb54e78b1b2308157ee75ee386e/test/utilities.js) of chaijs/chai.

As @meeber suggested [here](https://github.com/chaijs/chai/pull/799#issuecomment-247973900), I think that we should refactor this test and split it so it has a single assertion per test and better names.
I understand that `get-func-name` should not grow a lot and will probably stay very simple, but I don't see this as a good reason to not have good descriptive tests.

If you guys agree. I'll be very happy to make a PR addressing this.

**Comment by lucasfcosta** [comment]
I totally agree.
That would be great.
