### ISSUE TITLE
Duplicate module name on NPM

### ISSUE THREAD

**Issue by lucasfcosta** [chaijs/get-func-name#4]
Hello everyone,

Apparently we've got another module with this name on NPM right now, so we will need another name for this module.

I thought about `get-function-name-chai` or `get-fn-name`.

Any suggestions?

**Comment by vieiralucas** [comment]
`get-fn-name` LGTM

**Comment by vieiralucas** [comment]
Wait, https://www.npmjs.com/package/get-fn-name
`get-fn-name` is already taken to

**Comment by lucasfcosta** [comment]
Yes, `func-name` LGTM too.
If that was taken I'd suggest `fun-name` (noticed the pun?).

**Comment by vieiralucas** [comment]
Haha, last time I check func-name was open.
But maybe the same guys that attacked the Lucas syndicate last week are reading this issue.

**Comment by keithamus** [comment]
`func-name` seems good. Let's change the `package.json` and rename the repo before merging #3 then.

**Comment by keithamus** [comment]
Oh... `func-name` has been taken in the last 10 hours! What about `get-normalised-function-name` - a little verbose but definitely free!

**Comment by shvaikalesh** [comment]
What about scoped packages like `@chai/get-fn-name`?

**Comment by lucasfcosta** [comment]
@shvaikalesh not sure it would be a good idea to add that to the chai module scope since the main idea here is for everyone to use it if they want to.
How about `get-func-name` only?

**Comment by vieiralucas** [comment]
Agreed with @lucasfcosta 
`get-func-name`
GO GRAB IT FAST RUNNN

**Comment by shvaikalesh** [comment]
@lucasfcosta that does not limit them to use it, but saves us from the pain of name choosing

**Comment by lucasfcosta** [comment]
@shvaikalesh Yes, that makes total sense. I do not have a strong opinion about it, I just thought it would be easier to grab an available name which is semantically the same. Anyway your idea is great too, I'd be happy to do whatever the team prefers 😄

**Comment by vieiralucas** [comment]
@shvaikalesh It does not limit people from using it. But IMHO it makes a little weird.
I think that we should strive a bit to find a short name available on npm that describes the lib first

**Comment by meeber** [comment]
I'm fine with either option

**Comment by shvaikalesh** [comment]
We have couple modules published w/o namespace, starting using scoped packages now will be a bit weird, we would have to republish all existing repos with `@chai` namespace to avoid confusion...

**Comment by keithamus** [comment]
Ahh! No tokens have been set! https://travis-ci.org/chaijs/get-function-name/jobs/166248698#L1033-L1034

**Comment by keithamus** [comment]
Okay, I've set the tokens and rebuilt. Should be released soon.

**Comment by vieiralucas** [comment]
So,
After merging #7 and fighting a lot with saucelabs
`get-func-name` is finnaly available on npm 🎉 🎉 🎉
