### ISSUE TITLE
The 2.0.1 release should be marked as 3.0.0

### ISSUE THREAD

**Issue by pomek** [chaijs/get-func-name#41]
The latest release ([2.0.1](https://www.npmjs.com/package/get-func-name/v/2.0.1)) includes the project conversion to ESM (#28), which seems to be a huge breaking change and should be released as a new major version.

Today, I wanted to execute unit tests using [Mocha](https://www.npmjs.com/package/mocha) (`^7`) and [chai](https://www.npmjs.com/package/chai) (^4) stack. Unfortunately, it ends with the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/circleci/project/node_modules/get-func-name/index.js from /home/circleci/project/node_modules/chai/lib/chai/utils/inspect.js not supported.
Instead change the require of index.js in /home/circleci/project/node_modules/chai/lib/chai/utils/inspect.js to a dynamic import() which is available in all CommonJS modules
...
```

Could I ask to revert the latest release to bring back compatibility in the `^2` version chain and consider releasing the converted project as a new major (`^3`)?

**Comment by wuriyanto48** [comment]
same issue here

**Comment by skunapareddy-reputation** [comment]
@keithamus could u please resolve this at the earliest our tests have taken a hit because of this release

**Comment by keithamus** [comment]
There's a `2.0.2` release which should fix the issue.

**Comment by mvtm-dn** [comment]
Still 2.0.1 @ npmjs

**Comment by pomek** [comment]
I confirm that version 2.0.2 brings back the compatibility and works as expected. Feel free to close the issue. Thank you for the rapid reaction.

**Comment by keithamus** [comment]
> Still 2.0.1 @ npmjs

Probably a caching issue...

```
❯ npm show get-func-name@2.0.2

get-func-name@2.0.2 | MIT | deps: none | versions: 5
Utility for getting a function's name for node and the browser
https://github.com/chaijs/get-func-name#readme
```

https://www.npmjs.com/package/get-func-name/v/2.0.2
